### ISSUE TITLE
Undefined Error

### ISSUE THREAD

**Issue by sibijohn72** [tzellman/ember-cordova-example-app#1]
Hi, I am getting this error while running the ember cdv : build command for this project. I have been following the instructions word by word. any help would be greatly appreciated.

`ERROR: ember-cordova
undefined
Error: ERROR: ember-cordova
undefined
    at Object.module.exports.error (C:\Y\ember-cordova-example-app\node_modules\
ember-cordova\lib\utils\logger.js:21:11)
    at C:\Y\ember-cordova-example-app\node_modules\ember-cordova\lib\commands\bu
ild.js:111:16
    at tryCatch (C:\Y\ember-cordova-example-app\node_modules\ember-cordova\node_
modules\rsvp\dist\rsvp.js:538:12)
    at invokeCallback (C:\Y\ember-cordova-example-app\node_modules\ember-cordova
\node_modules\rsvp\dist\rsvp.js:553:13)
    at publish (C:\Y\ember-cordova-example-app\node_modules\ember-cordova\node_m
odules\rsvp\dist\rsvp.js:521:7)
    at publishRejection (C:\Y\ember-cordova-example-app\node_modules\ember-cordo
va\node_modules\rsvp\dist\rsvp.js:456:3)
    at flush (C:\Y\ember-cordova-example-app\node_modules\ember-cordova\node_mod
ules\rsvp\dist\rsvp.js:2373:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)`

**Comment by tzellman** [comment]
Are you still having a problem? I'm not sure how to replicate the issue you are having. If you have any additional details to add I'd be happy to take a closer look.

**Comment by sibijohn72** [comment]
I have fixed the issue. I'll merge the fix soon. Meanwhile if you have time could you also add a demo on how to add fingerprint authentication.
